-- MySQL Script generated by MySQL Workbench
-- Mon Sep 16 14:10:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nivel` ENUM('Cliente', 'Adm', 'Funcionario') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `celular` VARCHAR(14) NOT NULL,
  `nascimento` DATE NOT NULL,
  `login_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`, `login_id`, `endereco_id`),
  INDEX `fk_cliente_login1_idx` (`login_id` ASC),
  INDEX `fk_cliente_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_cliente_login1`
    FOREIGN KEY (`login_id`)
    REFERENCES `mydb`.`Login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Endereco_id`),
  INDEX `fk_Empresa_Endereco1_idx` (`Endereco_id` ASC),
  CONSTRAINT `fk_Empresa_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `celular` VARCHAR(14) NOT NULL,
  `nascimento` DATE NOT NULL,
  `login_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  `Empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`, `login_id`, `endereco_id`, `Empresa_id`),
  INDEX `fk_funcionario_login1_idx` (`login_id` ASC),
  INDEX `fk_funcionario_endereco1_idx` (`endereco_id` ASC),
  INDEX `fk_Funcionario_Empresa1_idx` (`Empresa_id` ASC),
  CONSTRAINT `fk_funcionario_login1`
    FOREIGN KEY (`login_id`)
    REFERENCES `mydb`.`Login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Empresa1`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque_entrada` (
  `idestoque` INT NOT NULL AUTO_INCREMENT,
  `Empresa_id` INT NOT NULL,
  `Empresa_Endereco_id` INT NOT NULL,
  PRIMARY KEY (`idestoque`, `Empresa_id`, `Empresa_Endereco_id`),
  INDEX `fk_Estoque_entrada_Empresa1_idx` (`Empresa_id` ASC, `Empresa_Endereco_id` ASC),
  CONSTRAINT `fk_Estoque_entrada_Empresa1`
    FOREIGN KEY (`Empresa_id` , `Empresa_Endereco_id`)
    REFERENCES `mydb`.`Empresa` (`id` , `Endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `validade` DATE NOT NULL,
  `data_entrada` DATE NOT NULL,
  `data_saida` DATE NULL,
  `preco_compra` DECIMAL(5,2) NOT NULL,
  `preco_venda` DECIMAL(5,2) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Categoria` ENUM('Alimentos', 'Eletrodomesticos', 'Telefonia', 'Informatica', 'Moveis', 'Higiene') NOT NULL,
  `Quantidade` INT NOT NULL,
  `Imagem1` VARCHAR(45) NOT NULL,
  `Imagem2` VARCHAR(45) NULL,
  `Imagem3` VARCHAR(45) NULL,
  `Estoque_entrada_idestoque` INT NOT NULL,
  `Estoque_entrada_Empresa_id` INT NOT NULL,
  `Estoque_entrada_Empresa_Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Estoque_entrada_idestoque`, `Estoque_entrada_Empresa_id`, `Estoque_entrada_Empresa_Endereco_id`),
  INDEX `fk_Produto_Estoque_entrada1_idx` (`Estoque_entrada_idestoque` ASC, `Estoque_entrada_Empresa_id` ASC, `Estoque_entrada_Empresa_Endereco_id` ASC),
  CONSTRAINT `fk_Produto_Estoque_entrada1`
    FOREIGN KEY (`Estoque_entrada_idestoque` , `Estoque_entrada_Empresa_id` , `Estoque_entrada_Empresa_Endereco_id`)
    REFERENCES `mydb`.`Estoque_entrada` (`idestoque` , `Empresa_id` , `Empresa_Endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Encomenda_saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Encomenda_saida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `data_entrada_pedido` DATE NULL,
  `data_entrega_pedido` DATE NULL,
  `valor_total` DECIMAL(7,2) NOT NULL,
  `Cliente_id` INT NOT NULL,
  `Cliente_login_id` INT NOT NULL,
  `Cliente_endereco_id` INT NOT NULL,
  `Empresa_id` INT NOT NULL,
  `Empresa_Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Cliente_id`, `Cliente_login_id`, `Cliente_endereco_id`, `Empresa_id`, `Empresa_Endereco_id`),
  INDEX `fk_Encomenda_saida_Cliente1_idx` (`Cliente_id` ASC, `Cliente_login_id` ASC, `Cliente_endereco_id` ASC),
  INDEX `fk_Encomenda_saida_Empresa1_idx` (`Empresa_id` ASC, `Empresa_Endereco_id` ASC),
  CONSTRAINT `fk_Encomenda_saida_Cliente1`
    FOREIGN KEY (`Cliente_id` , `Cliente_login_id` , `Cliente_endereco_id`)
    REFERENCES `mydb`.`Cliente` (`id` , `login_id` , `endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Encomenda_saida_Empresa1`
    FOREIGN KEY (`Empresa_id` , `Empresa_Endereco_id`)
    REFERENCES `mydb`.`Empresa` (`id` , `Endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_encomenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_encomenda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Quantidade` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `Produto_Estoque_entrada_idestoque` INT NOT NULL,
  `Produto_Estoque_entrada_Empresa_id` INT NOT NULL,
  `Produto_Estoque_entrada_Empresa_Endereco_id` INT NOT NULL,
  `Encomenda_saida_id` INT NOT NULL,
  `Encomenda_saida_Cliente_id` INT NOT NULL,
  `Encomenda_saida_Cliente_login_id` INT NOT NULL,
  `Encomenda_saida_Cliente_endereco_id` INT NOT NULL,
  `Encomenda_saida_Empresa_id` INT NOT NULL,
  `Encomenda_saida_Empresa_Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Produto_id`, `Produto_Estoque_entrada_idestoque`, `Produto_Estoque_entrada_Empresa_id`, `Produto_Estoque_entrada_Empresa_Endereco_id`, `Encomenda_saida_id`, `Encomenda_saida_Cliente_id`, `Encomenda_saida_Cliente_login_id`, `Encomenda_saida_Cliente_endereco_id`, `Encomenda_saida_Empresa_id`, `Encomenda_saida_Empresa_Endereco_id`),
  INDEX `fk_Produto_encomenda_Produto1_idx` (`Produto_id` ASC, `Produto_Estoque_entrada_idestoque` ASC, `Produto_Estoque_entrada_Empresa_id` ASC, `Produto_Estoque_entrada_Empresa_Endereco_id` ASC),
  INDEX `fk_Produto_encomenda_Encomenda_saida1_idx` (`Encomenda_saida_id` ASC, `Encomenda_saida_Cliente_id` ASC, `Encomenda_saida_Cliente_login_id` ASC, `Encomenda_saida_Cliente_endereco_id` ASC, `Encomenda_saida_Empresa_id` ASC, `Encomenda_saida_Empresa_Endereco_id` ASC),
  CONSTRAINT `fk_Produto_encomenda_Produto1`
    FOREIGN KEY (`Produto_id` , `Produto_Estoque_entrada_idestoque` , `Produto_Estoque_entrada_Empresa_id` , `Produto_Estoque_entrada_Empresa_Endereco_id`)
    REFERENCES `mydb`.`Produto` (`id` , `Estoque_entrada_idestoque` , `Estoque_entrada_Empresa_id` , `Estoque_entrada_Empresa_Endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_encomenda_Encomenda_saida1`
    FOREIGN KEY (`Encomenda_saida_id` , `Encomenda_saida_Cliente_id` , `Encomenda_saida_Cliente_login_id` , `Encomenda_saida_Cliente_endereco_id` , `Encomenda_saida_Empresa_id` , `Encomenda_saida_Empresa_Endereco_id`)
    REFERENCES `mydb`.`Encomenda_saida` (`id` , `Cliente_id` , `Cliente_login_id` , `Cliente_endereco_id` , `Empresa_id` , `Empresa_Endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
