-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 16:31:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dados` (
  `idDados` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone1` VARCHAR(13) NOT NULL,
  `Telefone2` VARCHAR(13) NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  `Nascimento` DATE NOT NULL,
  PRIMARY KEY (`idDados`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Dados_idDados` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Dados1_idx` (`Dados_idDados` ASC),
  CONSTRAINT `fk_Cliente_Dados1`
    FOREIGN KEY (`Dados_idDados`)
    REFERENCES `mydb`.`Dados` (`idDados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Dados_idDados` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Dados1_idx` (`Dados_idDados` ASC),
  CONSTRAINT `fk_Usuario_Dados1`
    FOREIGN KEY (`Dados_idDados`)
    REFERENCES `mydb`.`Dados` (`idDados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(18) NOT NULL,
  `Contato1` VARCHAR(13) NOT NULL,
  `Contato2` VARCHAR(13) NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `Usuario_idUsuario` INT, -- (IAGO) EU REMOVI O NOT NULL DISSO PARA FAZER OS TESTES
  PRIMARY KEY (`idEmpresa`),
  INDEX `fk_Empresa_Usuario1_idx` (`Usuario_idUsuario` ASC),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC),
  CONSTRAINT `fk_Empresa_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `Dados_idDados` INT NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Funcionario_Dados_idx` (`Dados_idDados` ASC),
  INDEX `fk_Funcionario_Empresa1_idx` (`Empresa_idEmpresa` ASC),
  CONSTRAINT `fk_Funcionario_Dados`
    FOREIGN KEY (`Dados_idDados`)
    REFERENCES `mydb`.`Dados` (`idDados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `mydb`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loginfuncionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loginfuncionario` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(20) NOT NULL,
  `Senha` VARCHAR(16) NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Login_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logincliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logincliente` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(20) NOT NULL,
  `Senha` VARCHAR(16) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Logincliente_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Logincliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loginusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loginusuario` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(20) NOT NULL,
  `Senha` VARCHAR(16) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Loginusuario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Loginusuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Validade` DATE NOT NULL,
  `P_compra` DECIMAL(4,2) NOT NULL,
  `P_venda` DECIMAL(4,2) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Quantidade` INT NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Imagem1` VARCHAR(255) NOT NULL,
  `Imagem2` VARCHAR(45) NOT NULL,
  `Imagem3` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `Empresa_idEmpresa` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`idEstoque`),
  INDEX `fk_Estoque_Empresa1_idx` (`Empresa_idEmpresa` ASC),
  INDEX `fk_Estoque_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Estoque_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `mydb`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Encomenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Encomenda` (
  `idEncomenda` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NOT NULL,
  `Data_entrada` DATE NOT NULL,
  `Data_saida` DATE NOT NULL,
  `Valor_total` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idEncomenda`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_encomenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_encomenda` (
  `idProduto_encomenda` INT NOT NULL AUTO_INCREMENT,
  `Encomenda_idEncomenda` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`idProduto_encomenda`),
  INDEX `fk_Produto_encomenda_Encomenda1_idx` (`Encomenda_idEncomenda` ASC),
  INDEX `fk_Produto_encomenda_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Produto_encomenda_Encomenda1`
    FOREIGN KEY (`Encomenda_idEncomenda`)
    REFERENCES `mydb`.`Encomenda` (`idEncomenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_encomenda_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
